version: "3.1"

services:
  hdpmst:
    image: mkenjis/ubhdp_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    volumes:
      - .:/root/staging
    networks:
      - mynet

  spk_mst:
    image: mkenjis/ubpyspkcli_yarn_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
      replicas: 1
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    ports:
      - 4040:4040
      - 8082:8082

  mysql:
    image: mysql:5.7
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=admsys123
      - MYSQL_DATABASE=metastore
      - MYSQL_USER=hiveuser
      - MYSQL_PASSWORD=hive123
    volumes:
      - .:/root/staging
      - db:/var/lib/mysql

networks:
  mynet:
    external:
       name: mynet

volumes:
  db: